pool:
  vmImage: 'windows-2019'
steps:
- script: |
    npm install @abaplint/cli -g
  displayName: 'abaplint Install'
- task: AzurePowerShell@4
  displayName: 'Download abaplint config from mounted storage account'
  inputs:
    azureSubscription: 'GSI_EM_AZ1_RG_FAST_SA'
    ScriptType: 'InlineScript'
    Inline: |
      $ResourceGroupName = "GSI-EM-AZ1-RG-FAST-SA"
      $StorageAccountName = "gsiemaz1dmzfastsa0001"
      $StorageAccountKey = (Get-AzStorageAccountKey -ResourceGroupName $ResourceGroupName -AccountName $StorageAccountName).Value[0]
      $StorageContext = New-AzStorageContext -StorageAccountName $StorageAccountName -StorageAccountKey $StorageAccountKey
      $FileName = 'abaplint.json'
      $OutputPath = '$(Agent.BuildDirectory)\s\'
      $ContainerName  = 'abaplint'
      Get-AzStorageBlobContent -Blob $FileName -Container $ContainerName -Destination $OutputPath -Context $StorageContext -Force
    azurePowerShellVersion: 'LatestVersion'
#- checkout: git://GCC FAST Core/abaplint_configuration
#  path: abaplint_conf
#- checkout: self
# - task: CopyFiles@2
#   inputs:
#     SourceFolder: '$(Agent.BuildDirectory)\abaplint_conf'
#     Contents: 'abaplint.json'
#     TargetFolder: '$(Agent.BuildDirectory)\s\MM_PO_CONF'
#   displayName: 'Copy abaplint.json to repo'
- script: |
    ls $(Agent.BuildDirectory)\s
  displayName: 'LS'
- script: |
    abaplint --version
  displayName: 'abaplint Version'
- script: |
    cd $(Agent.BuildDirectory)\s &
    abaplint -f standard --outformat junit --outfile $(Agent.BuildDirectory)\s\report.xml || true
  displayName: 'abaplint Run'
- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: 'report.xml'
    failTaskOnFailedTests: false