trigger:
- main

pool:
  vmImage: ubuntu-latest

resources:
  repositories:
  - repository: MyGitHubRepo # The name used to reference this repository in the checkout step
    type: github
    endpoint: netweaverdlw
    name: netweaverdlw/ABAP_MM_PO_CONF

steps:
- checkout: self
- checkout: MyGitHubRepo
# - script: |
#     cp -r MM_PO_CONF/. ABAP_MM_PO_CONF/
# - script: |
#     cp -R MM_PO_CONF ABAP_MM_PO_CONF

# - script: |
#     rsync -av --progress MM_PO_CONF ABAP_MM_PO_CONF --exclude .git
#   displayName: 'Copy file content to local folder of GitHub repo'
# - script: |
#     rsync -av --progress MM_PO_CONF/. ABAP_MM_PO_CONF/ --exclude .git
#   displayName: 'Copy file content to local folder of GitHub repo'
# - script: |
#     rsync -av --progress MM_PO_CONF/. ABAP_MM_PO_CONF/
#   displayName: 'Copy file content to local folder of GitHub repo'

- script: ls -hal ABAP_MM_PO_CONF
  displayName: 'List local GitHub repo contents'

- script: |
    cd ABAP_MM_PO_CONF
    git status
  displayName: 'Check git status'

# pool:
#   vmImage: 'windows-2019'
# steps:
# - script: |
#     npm install @abaplint/cli -g
#   displayName: 'abaplint Install'
# - task: AzurePowerShell@4
#   displayName: 'Download abaplint config from mounted storage account'
#   inputs:
#     azureSubscription: 'GSI_EM_AZ1_RG_FAST_SA'
#     ScriptType: 'InlineScript'
#     Inline: |
#       $ResourceGroupName = "GSI-EM-AZ1-RG-FAST-SA"
#       $StorageAccountName = "gsiemaz1dmzfastsa0001"
#       $StorageAccountKey = (Get-AzStorageAccountKey -ResourceGroupName $ResourceGroupName -AccountName $StorageAccountName).Value[0]
#       $StorageContext = New-AzStorageContext -StorageAccountName $StorageAccountName -StorageAccountKey $StorageAccountKey
#       $FileName = 'abaplint.json'
#       $OutputPath = '$(Agent.BuildDirectory)\s\'
#       $ContainerName  = 'abaplint'
#       Get-AzStorageBlobContent -Blob $FileName -Container $ContainerName -Destination $OutputPath -Context $StorageContext -Force
#     azurePowerShellVersion: 'LatestVersion'
# - script: |
#     abaplint --version
#   displayName: 'abaplint Version'