trigger:
- main

pool:
  vmImage: ubuntu-latest

resources:
  repositories:
  - repository: MyGitHubRepo
    type: github
    endpoint: netweaverdlw
    name: netweaverdlw/ABAP_MM_PO_CONF

steps:
- checkout: self
- checkout: MyGitHubRepo
  persistCredentials: true
  clean: true

- script: rsync -av --progress MM_PO_CONF/. ABAP_MM_PO_CONF/ --exclude .git
  displayName: 'Copy file content to local folder of GitHub repo'

- script: ls -hal ABAP_MM_PO_CONF
  displayName: 'List local GitHub repo contents'

- script: |
    cd ABAP_MM_PO_CONF
    git add .
  displayName: 'Stage untracked files'

- script: |
    cd ABAP_MM_PO_CONF
    git status
  displayName: 'Check git status'

- script: |
    cd ABAP_MM_PO_CONF
    git config --global user.email "brecht.heldens@delaware.pro"
    git config --global user.name "BHeldens"
    git commit -m 'Automated sync from DevOps'
  displayName: 'Commit staged files'

- script: |
    cd ABAP_MM_PO_CONF
    git push origin HEAD:main
  displayName: 'Push commit'