trigger:
- main

pool:
  vmImage: ubuntu-latest

resources:
  repositories:
  - repository: MyGitHubRepo # The name used to reference this repository in the checkout step
    type: github
    endpoint: netweaverdlw
    name: netweaverdlw/ABAP_MM_PO_CONF

steps:
- checkout: self
- checkout: MyGitHubRepo

- script: rsync -av --progress MM_PO_CONF/. ABAP_MM_PO_CONF/ --exclude .git
  displayName: 'Copy file content to local folder of GitHub repo'

- script: ls -hal ABAP_MM_PO_CONF
  displayName: 'List local GitHub repo contents'

- script: |
    cd ABAP_MM_PO_CONF
    git add .
  displayName: 'Stage untracked files'

- script: |
    cd ABAP_MM_PO_CONF
    git status
  displayName: 'Check git status'

- script: |
    cd ABAP_MM_PO_CONF
    git commit -m 'Automated sync from DevOps'
  displayName: 'Commit staged files'