 CLASS /df5/tcl_poconf_head  DEFINITION
 PUBLIC
 FINAL
 CREATE PUBLIC
 FOR TESTING.

   PUBLIC SECTION.
   PROTECTED SECTION.
   PRIVATE SECTION.
 ENDCLASS.

 CLASS /df5/tcl_poconf_head  IMPLEMENTATION.
 ENDCLASS.
