 CLASS /df5/tcl_poconf_sum  DEFINITION
 PUBLIC
 FINAL
 CREATE PUBLIC
 FOR TESTING.

   PUBLIC SECTION.
   PROTECTED SECTION.
   PRIVATE SECTION.
 ENDCLASS.

 CLASS /df5/tcl_poconf_sum  IMPLEMENTATION.
 ENDCLASS.
