 CLASS /df5/tcl_eket_deldate  DEFINITION
 PUBLIC
 FINAL
 CREATE PUBLIC
 FOR TESTING.

   PUBLIC SECTION.
   PROTECTED SECTION.
   PRIVATE SECTION.
 ENDCLASS.

 CLASS /df5/tcl_eket_deldate  IMPLEMENTATION.
 ENDCLASS.
